### ISSUE TITLE
Kodi Error

### ISSUE THREAD

**Issue by hidemyassbaby** [matthuisman/repository.matthuisman#1]
![image](https://user-images.githubusercontent.com/49113438/55667578-6d27d880-58ba-11e9-8f5c-b9c9d3fc36f5.png)

**Comment by matthuisman** [comment]
What addon?

**Comment by hidemyassbaby** [comment]
TVNZ On demand, freeview or Three Now

Trying to use these as a widget on kodi

Skin aura (18) on kodi 18.1

**Comment by matthuisman** [comment]
My plugins don't support widgets, but if you get me a debug log - I may be able to sort something

**Comment by hidemyassbaby** [comment]
https://paste.ubuntu.com/p/f8DX2KYQPD/

Example log when I added the Three Now as a widget errors

**Comment by hidemyassbaby** [comment]
I would love to have widgets if it was possible

**Comment by matthuisman** [comment]
I see. It adds a reload param.
I should be able to update all my plugins to ignore any extra arguments

**Comment by hidemyassbaby** [comment]
That would be Amazing

I would like to use tvnz on demand three now and freeview nz as a widget

**Comment by hidemyassbaby** [comment]
I would love to have widgets if it was possible

**Comment by matthuisman** [comment]
I've just pushed updates to all three of those add-ons that should allow them to work with widgets.
You can force updates by navigating to my repo, open context menu and click "Check for updates"

**Comment by matthuisman** [comment]
The other addons widgets working now?
